#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NN.DiscoWarrantyPlugin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Services.Plugins;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Configuration.cshtml")]
    public partial class Configuration : System.Web.Mvc.WebViewPage<NN.DiscoWarrantyPlugin.ViewModels.ConfigurationModel>
    {
        public Configuration()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" style=\"width: 600px; margin: 0 auto;\"");

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 131), Tuple.Create("\"", 179)
            
            #line 3 "..\..\Views\Configuration.cshtml"
, Tuple.Create(Tuple.Create("", 137), Tuple.Create<System.Object, System.Int32>(this.DiscoPluginResourceUrl("NNLogo.png")
            
            #line default
            #line hidden
, 137), false)
);

WriteLiteral(" alt=\"NN\"");

WriteLiteral(" style=\"float: left; width: 192px; height: 202px;\"");

WriteLiteral(" />\r\n    <h3");

WriteLiteral(" style=\"float: left; margin-top: 80px; margin-left: 20px;\"");

WriteLiteral(@">This plugin doesn't require any configuration.</h3>
    <h4>Disclaimer</h4>
    <p>Network Neighborhood does not provide technical support for the plugin and NN will not be liable for loss or damages in relation to the use of this plugin. <br /> This plugin was developed by Sean Benham and if requested by Network Neighborhood the plugin could be disabled at anytime.</p>
</div>
<script>
    $(function () {
        var $actionBar = $('.actionBar');

        // Remove the 'Save Configuration' button
        $actionBar.find('input[type=""submit""][value=""Save Configuration""]').remove();

        // Add 'Return to Plugins' button
        var pluginsUrl = '");

            
            #line 16 "..\..\Views\Configuration.cshtml"
                      Write(Url.Content("~/Config/Plugins"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var $buttonPlugins = $(\'<a>\').attr(\'href\', pluginsUrl).addClass(\'butt" +
"on\').text(\'Return to Plugins\').prependTo($actionBar);\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
