#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NN.DiscoWarrantyPlugin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Services.Plugins;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/NNOptions.cshtml")]
    public partial class NNOptions : System.Web.Mvc.WebViewPage<Disco.Services.Plugins.NN.ViewModels.NNOptionsViewModel>
    {
        public NNOptions()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\NNOptions.cshtml"
  
       
                        // NN Options
                        // Last Updated 20/05/2013
                        // Sean Benham
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n<div");

WriteLiteral(" id=\"warrantyJobFaultDescription\"");

WriteLiteral(" class=\"form\"");

WriteLiteral(" style=\"width: 650px; margin-top: 15px;\"");

WriteLiteral(">\r\n    <h2>Warranty Options</h2>\r\n    <table>\r\n\r\n        <tr>\r\n            <td>\r\n" +
"\r\n                <p>\r\n                    Please state the type of claim you wi" +
"sh to submit:\r\n                    <br />\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\NNOptions.cshtml"
               Write(Html.RadioButtonFor(m => m.NTPDevice, false));

            
            #line default
            #line hidden
WriteLiteral(" School Owned Device <br />\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Views\NNOptions.cshtml"
               Write(Html.RadioButtonFor(m => m.NTPDevice, true));

            
            #line default
            #line hidden
WriteLiteral(" Victorian NTP Staff Notebook  <br />\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\NNOptions.cshtml"
               Write(Html.ValidationMessageFor(m => m.NTPDevice));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </p>\r\n                <p>\r\n                    What is the prim" +
"ary suspected issue with the device:\r\n                    <br />\r\n              " +
"     \r\n                    \r\n\r\n");

            
            #line 32 "..\..\Views\NNOptions.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 32 "..\..\Views\NNOptions.cshtml"
                      
                        
                        // Drop Down box with values
                        var issues = new Dictionary<int, string> 
                              {
                                    { 0, "Please Select"},
                                    { 1, "Hard Drive"},
                                    { 2, "CPU"},
                                    { 3, "Charger"},
                                    { 4, "RAM"},
                                    { 5, "Motherboard"},
                                    { 6, "Keyboard"},
                                    { 7, "Palmrest"},
                                    { 8, "DVD Drive"},
                                    { 9, "Screen"},
                                    { 10, "Physical Screen Damage"},
                                    { 11, "Physical Base"},
                                    { 12, "Physical Top Cover"},
                                    { 13, "Physical Keyboard"},
                                    { 14, "Physical Charger"},
                                    { 15, "Battery"},
                                    { 16, "Physical Battery"},
                                    { 17, "Basecover"},
                                    { 18, "Screen Hinges"},
                                    { 19, "Fan"},
                                    { 20, "Internal Power"}
                            };
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 60 "..\..\Views\NNOptions.cshtml"
               Write(Html.DropDownListFor(m => m.Issue, new SelectList(issues, "Key", "Value")));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 61 "..\..\Views\NNOptions.cshtml"
               Write(Html.ValidationMessageFor(m => m.Issue));

            
            #line default
            #line hidden
WriteLiteral("                \r\n\r\n                </p>\r\n\r\n            </td>\r\n        </tr>\r\n   " +
" </table>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
