#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disco.Services.Plugins.NN.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Services.Plugins;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Configuration.cshtml")]
    public partial class Configuration : System.Web.Mvc.WebViewPage<Disco.Services.Plugins.NN.ViewModels.ConfigurationModel>
    {
        public Configuration()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h2>Network Neighbourhood Warranty Plugin</h2>\r\n<img");

WriteLiteral(" src=\"http://www.nn.net.au/images/website/NNLogo.png\"");

WriteLiteral(" alt=\"NN\"");

WriteLiteral(" /> \r\n<h3>This plugin doesn\'t require any configuration. Contact details are supp" +
"lied by Active Directory.</h3>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
